### ISSUE TITLE
publish odometry in ENU

### ISSUE THREAD

**Issue by sei-jmattson** [heuristicus/spot_ros#108]
If I understand correctly, this driver publishes Odometry as a NED frame.
Any interest in a PR adding param `~publish_odom_as_enu` and transforming, or is that better left to an external node?

**Comment by jeremysee2** [comment]
Personally, I haven't experienced requiring ENU for this specific robot. Switching between ENU and NED seems simple enough that I don't think it needs to be part of this wrapper, whose main purpose is to serve as middleware between Boston Dynamics' SDK and ROS.

**Comment by heuristicus** [comment]
We're getting odometry data here

https://github.com/heuristicus/spot_ros/blob/3fbb763aee621c213dc63130024067f3089254ca/spot_driver/src/spot_driver/ros_helpers.py#L372-L405

My preference is to keep things such that we're providing the exact data that is output by the robot, rather than doing anything to modify it (unless it is otherwise necessary to display the state of the system). If it's necessary to do odometry conversions for an application, then that should be done with a customised node.

**Comment by sei-jmattson** [comment]
Sounds good, thanks.  We'll go with an external transform.
