### ISSUE TITLE
tf transform between 'odom' and 'body' seems wrong

### ISSUE THREAD

**Issue by zkytony** [heuristicus/spot_ros#71]
In the screenshot below,
![image](https://user-images.githubusercontent.com/7720184/156898846-0c3ab5c5-1f59-478e-b9ad-d1d9a2f99e72.png)

The robot is sitting on a dock, but the height difference between the odom frame and the body frame is too much. 
I have tried restarting the driver, and the height difference would vary (there are times when the height seems to be reasonable, but it is very rare). What could be the reason?

**Comment by heuristicus** [comment]
This is caused by odometry drift. If you reboot the robot you should see that the odometry starts zeroed. If you move the robot around, the odometry will drift in the x-y coordinates. But, the z-offset drifts regardless of whether the robot is in motion, which I suspect is caused by IMU drift.

You should not rely on odometry to provide you with an accurate position of the robot. Over short periods of time the estimate is good, but over long periods is is unreliable.

**Comment by zkytony** [comment]
The thing is It didn't move the robot around, and it would start with an incorrect height (the robot is just staying on the dock the whole time). 

I did observe this (the odom frame starts overlapping with body almost entirely when the robot boots).
> If you reboot the robot you should see that the odometry starts zeroed. 

I see. Thanks for confirming this.
> the z-offset drifts regardless of whether the robot is in motion, which I suspect is caused by IMU drift.

I think you are probably right. The x-y drift happens when the robot moves, but the z-drift occurs regardless of movement.

**Comment by zkytony** [comment]
setting the parameter `mode_parent_odom_tf` to `vision` helped!
