### ISSUE TITLE
Simulation enviroment

### ISSUE THREAD

**Issue by mart-karelics** [heuristicus/spot_ros#73]
Hi, 

First of all thank  you for providing this driver. 

I was wondering if you are planning to release the code needed for simulation. It seems that the code exist for use on [AWS](https://aws.amazon.com/blogs/robotics/clearpath-enables-robotics-prototyping-one-click-simulations-using-aws/). It would be very beneficial for testing.

Even if it was just a docker container that would behave as a virtual spot 

Best Regards.

Mart

**Comment by METEORITENMAX** [comment]
Hello,

to my knowledge it is not possible to use this driver code directly for simulation, because the boston SDK doesn't include all the low level motion control functionalities which are necessary to control the simulated model.

We are working on a simulation of the spot in webots: https://github.com/MASKOR/webots_ros2_spot
Maybe this is something for you. 

If you're absolutely looking for a solution with ROS1 and gazebo, then Spot in AWS Robomaker might be an option:
https://github.com/SoftServeSAG/robotics_spot/tree/temp_robomaker.
This article describes the problem or the options a little bit: https://www.softserveinc.com/de-de/blog/spot-simulation-tools

I hope this helps you.

**Comment by mart-karelics** [comment]
Hi, 

Thanks for you response

In an ideal world boston dynamics would provide something like a docker simulating the behavior of the real spot. So that it would be possible to directly use this driver with the simulated robot. But as far as i understand now is that such simulation environment is not available.

I'm actually looking for a ROS2 solution preferably using gazebo as that is the tool we are currently using. You work on spot_ros2 and webots__spot looks very promising thanks for sharing.
