### ISSUE TITLE
spot urdf file missing Inertia and mass parameters

### ISSUE THREAD

**Issue by adamanov** [heuristicus/spot_ros#79]
Hello, 

using the given xacro model, I launched in gazebo empty world, however, the spot did not appear due to lackness of **inertial** and **mass** parameters. I set them randomly, and the spot appeared in the empty gazebo model. However, it would be nice to get real parameters if there are available, and update the current `spot.urdf.xacro` model

```
  <link name="anylink " >
....  
        <inertial>
            <mass value="5.0" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>

    </link>

```

**Comment by civerachb-cpr** [comment]
Because Spot's footstep planning is proprietary and runs wholly inside Spot's inner PC, we made the decision not to implement Gazebo-specific features like this.

You could probably contact Boston Dynamics' support to get more accurate values for the mass and inertia of the robot, though without BD's joint control any Gazebo simulation of Spot is unlikely to behave in a manner similar to the real robot.
