### ISSUE TITLE
Maintenance - Is this repo active?

### ISSUE THREAD

**Issue by EricVoll** [heuristicus/spot_ros#86]
Hi @dniewinski and others,

question: Is this repo actively maintained? The last commits to master are pretty old, and many open PRs could be merged.

Best
Eric

**Comment by heuristicus** [comment]
Hi Eric,

I was contacted by @tonybaltovski several months ago about potentially taking over maintenance, but haven't heard anything since august about that. I don't know if there have been discussions with others. I believe it would be fairly simple to give a few people admin control over this repo, but my understanding is that clearpath are no longer active in working with custom ROS interfaces for spot and would prefer to hand over to someone else. Because this repo is attached to their organisation right now, that would imply their responsibility for it in some sense, so I believe the intent was to move the repo elsewhere.

We discussed potentially archiving this repository and pointing to the repository that I've been updating on the side at https://github.com/ori-drs/spot_ros. I don't particularly like that approach since there's a lot of history in the issues/PRs which would be useful to have.

There is the option to transfer this repo in its entirety from clearpath's organisation to another, which would mean all the history, watchers, etc. would not have to do anything. That would be my preferred approach.

I've been checking the network history occasionally and there are quite a few people doing work in various areas to improve interaction, and some of them are likely duplicating at least some of their work. Having active maintenance here might encourage people to make more PRs and save time for everyone.

I'd appreciate an update from someone at clearpath about how to move forward. This repo is a great resource for people to get started quickly with ROS and spot, and having it stagnate would be unfortunate.

**Comment by EricVoll** [comment]
Hi @heuristicus 
thanks for the info. 
I work at Microsoft now and we're using Spot with this ros wrapper quite actively in different projects. I can ask internally if there is an option for Microsoft's GitHub Account to take over this repository (e.g. as a fork?).

I agree with you @heuristicus that we should keep this repository alive in some way.

**Comment by heuristicus** [comment]
As long as there's someone willing to actively maintain it I'm not attached to it going to any place specific. I spoke to people at my institute and there was no objection in principle to moving it to the https://github.com/ori-drs organisation. We are using it here for our spot, but it's only really me who has been using it actively. It probably makes sense for you or your team to be the organisational host if you have more resources available.

**Comment by EricVoll** [comment]
I think our resources are usually limited for non-prod work, so I'd be super glad if you could host it on the ori-drs account, that would be awesome. 

I can see the repo has been assigned to your account already (confused me for a second there :D)

**Comment by heuristicus** [comment]
OK, I'll make that change at some point soon. But at any rate now we can start merging stuff again.
